apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k8s-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-2
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: hello-k8s-2
  template:
    metadata:
      labels:
        app: hello-k8s-2
    spec:
      containers:
        - name: hello-k8s-2
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

